### ISSUE TITLE
`brew tap pulumi/tap` causes an error

### ISSUE THREAD

**Issue by SirensOfTitan** [pulumi/homebrew-tap#2]
`brew tap pulumi/tap` causes an error

## Expected behavior
Adding `pulumi/tap` as a brew tap succeeds and allows me to install crd2pulumi.

## Current behavior
Either doing `brew tap pulumi/tap` or `brew install pulumi/tap/crd2pulumi` fails with the following error: `formulae require at least a URL`

Full error from `brew tap pulumi/tap`:
```
Cloning into '/opt/homebrew/Library/Taps/pulumi/homebrew-tap'...
remote: Enumerating objects: 151, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 151 (delta 90), reused 7 (delta 2), pack-reused 0
Receiving objects: 100% (151/151), 28.53 KiB | 4.75 MiB/s, done.
Resolving deltas: 100% (90/90), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/pulumi/homebrew-tap/crd2pulumi.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/pulumi/homebrew-tap/tf2pulumi.rb
formulae require at least a URL
Error: Cannot tap pulumi/tap: invalid syntax in tap!
```

## Steps to reproduce
1. Ensure that `pulumi/tap` is not a brew tap.
2. `brew tap pulumi/tap`

## Context (Environment)
macOS 11.2.3 Big Sur
MacBook Pro 13" M1

## Affected feature

**Comment by stack72** [comment]
Hi @SirensOfTitan 

I am sorry this is happening for you - I was just able to successfully install things:

```
==> Installing crd2pulumi from pulumi/tap
==> Downloading https://github.com/pulumi/crd2pulumi/releases/download/v1.0.6/crd2pulumi-v1.0.6-darwin-amd64.tar.gz
==> Downloading from https://github-releases.githubusercontent.com/293952297/48c1de80-af0e-11eb-8b33-4afa2b862181?X-Amz-Algori
######################################################################## 100.0%
```

I will investigate the m1 setup of this repository and make sure the same experience happens

Paul

**Comment by stack72** [comment]
Hi @SirensOfTitan 

Just waiting on the final arm64 build to do into the tap - I have an M1 that I am seeing your issue on and I can see the issue moving to the broken project

I suspect it will be fixed in 30 mins - when you see this issue closed, then you will be able to take this for a spin

sorry again about this

Paul

**Comment by stack72** [comment]
You should be good to go now @SirensOfTitan 

I have just installed from this tap and the syntax errors go away
