### ISSUE TITLE
Automatically push to `master` when commits are pushed to `main`

### ISSUE THREAD

**Issue by justinvp** [pulumi/homebrew-tap#28]
We renamed the default branch from `master` to `main` which results in users seeing errors when trying to update `pulumi`, requiring `brew tap --repair` to fix-up their tap.

To remediate in the meantime, we've added back `master`. Now we need to keep `master` up-to-date with `main`. We should add a workflow that pushes to `master` on pushes to `main`.

**Comment by tgummerer** [comment]
This was fixed by https://github.com/pulumi/homebrew-tap/pull/29
